version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"  # MQTT port
      - "9001:9001"  # MQTT over WebSocket
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
