apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb-feeder
  labels:
    app: influxdb-feeder
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb-feeder
  template:
    metadata:
      labels:
        app: influxdb-feeder
    spec:
      containers:
        - name: influxdb-feeder
          image: rafaelvzago/influxdb-feeder:latest
          imagePullPolicy: Always # or IfNotPresent
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
