apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
  namespace: influxdb # Use the same namespace as your InfluxDB deployment
spec:
  selector:
    app: influxdb
  ports:
    - protocol: TCP
      port: 8086 # The port on which InfluxDB is running within the container
  type: ClusterIP
